api_key: " Add your api key here"
engine: "gpt-3.5-turbo"
proxy: null
max_tokens: 4000
temperature: 0.5
top_p: 1.0
timeout: 100
presence_penalty: 0.0
frequency_penalty: 0.0
truncate_limit: 3000
reply_count: 1
system_prompt: "You are ChatGPT, a large language model trained by OpenAI. Respond conversationally."

